on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Minor Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: python-packages
          path: media/*.qza
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'media/*.qza'
          body: |
            Please see https://github.com/micom-dev/micom_media/blob/main/NEWS.md for the full release notes.
            Use the links below to download media compositions from this particular release.
          draft: false
          prerelease: false
